import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/Common/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="p-4">
        <Header />
        <main className="flex-grow">{children}</main>
      </body>
    </html>
  );
}
