import type { Metadata } from "next";
import "./globals.css";
import HeaderWrapper from "@/components/Common/HeaderWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="flex flex-col items-center p-7">
        <HeaderWrapper />
        <main className="w-full max-w-4xl flex-grow">{children}</main>
      </body>
    </html>
  );
}
